### PR TITLE
Just copy the Rust lib instead of having a submodule.

### PR DESCRIPTION
**Pull request by sgnr**
Just to simplify development, I suggest we have the sources directly in this repository instead of having to deal with a submodule.

### CODE REVIEW

**Comment by sgnr** [comment]
One downside is that we lose Travis CI, but I think this is worth it. What do you think?

**Comment by maximg** [comment]
Agree it will be easier. I was thinking about Travis as well, also for the tutorial part, and I cannot imagine having 2 subprojects for this reason - so at some point we will have to find a solution for the whole of Thrift. I will open an issue to address this.

**Comment by maximg** [comment]
Hmm, is there a way on github to open an issue on a fork of a project? Maybe it is a bit too early in the morning...

**Comment by sgnr** [comment]
You have to enable issues in the project settings first.

**Comment by maximg** [comment]
Thanks!

https://github.com/maximg/thrift/issues/3

**Pull request merged**
