### PR TITLE
Use more stable features

### PR DESCRIPTION
**Pull request by mvdnes**
* Remove `as_slice`
* Switch from `FromPrimitive` to a custom generated `FromNum`
* Use the new `io` everywhere.

This should also fix any previous compilation issues.

### CODE REVIEW

**Comment by mvdnes** [comment]
Ah I forgot! Will do so this evening or tomorrow.

**Comment by mvdnes** [comment]
Updated the tutorial.
Also added a build script to the tutorial so that the thrift modules will automatically be generated upon first build.

**Comment by maximg** [comment]
Thanks! Merged everything except for the removal of generated files - for me they proved to be useful for tracking the changes in the compiler, so I'd rather keep them for now, and remove when the compiler becomes stable.

**Comment by mvdnes** [comment]
Yes that seems like a good idea :+1: Thanks for merging!

**Pull request merged**
